version: "3"
services:
  web:
    container_name: appnode
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: bdmongo
    image: mongo
    ports:
      - "27017:27017"
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: clave 
    logging:
      driver: none
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 90:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: clave
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
