version: "3" # versión con la que vamos a trabajar
services:  # los servicios que voy a usar
  app:  # nombre del contenedor
    container_name: appnode #nombre del contenedor
    restart: always # cuando inicia el contenedor siempre se reinicia
    build: . #que el archivo se contruya de raíz (docker file) el punto es para que se contruya de forma automatica
    ports:  # puertos
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app # copia todo lo que existe en esta ubicación 
  mongo:  # nombre del contenedor
    container_name: bdmongo #nombre del contenedor (mi identificador)
    image: mongo #nombre de la imagen (en nuestro caso la imagen más nueva será usada)
    ports: # puertos, usaré el 27018 para evitar conflictos con mongo de forma local
      - "27018:27017"
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: clave

  mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=root
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=clave
            - ME_CONFIG_BASICAUTH_USERNAME=MONGOEXPRESS_LOGIN
            - ME_CONFIG_BASICAUTH_PASSWORD=MONGOEXPRESS_PASSWORD
            - ME_CONFIG_MONGODB_URL=mongodb://root:clave@mongo:27017/
        depends_on:
            - mongo
        ports:
          - "8080:8081"